Repository OjoRise/BackEnd, pull requests merged in 2025-06, with the labels that each got.

#29 Ojorise 52 add recommended and liked plans api
  src/main/java/com/uplus/ojorise/controller/AuthController.java
  src/main/java/com/uplus/ojorise/controller/DipPlanController.java
  src/main/java/com/uplus/ojorise/controller/RecommendPlanController.java
  src/main/java/com/uplus/ojorise/domain/DipPlan.java
  src/main/java/com/uplus/ojorise/domain/RecommendPlan.java
  src/main/java/com/uplus/ojorise/dto/RecommendPlanRequest.java
  src/main/java/com/uplus/ojorise/mapper/DipPlanMapper.java
  src/main/java/com/uplus/ojorise/mapper/RecommendPlanMapper.java
  src/main/java/com/uplus/ojorise/service/DipPlanService.java
  src/main/java/com/uplus/ojorise/service/RecommendPlanService.java
  src/main/resources/application.properties
  src/main/resources/mapper/PlanMapper.xml
Labels: enhancement

#41 OJORISE-63-screenshot-functions
  src/main/resources/mapper/SurveyMapper.xml
Labels: duplicate

#42 OJORISE-82-add-user-api
  src/main/java/com/uplus/ojorise/config/JwtAuthenticationFilter.java
  src/main/java/com/uplus/ojorise/config/SecurityConfig.java
  src/main/java/com/uplus/ojorise/controller/DipPlanController.java
  src/main/java/com/uplus/ojorise/controller/ProfileController.java
  src/main/java/com/uplus/ojorise/controller/UserController.java
  src/main/java/com/uplus/ojorise/domain/Profile.java
  src/main/java/com/uplus/ojorise/mapper/DipPlanMapper.java
  src/main/java/com/uplus/ojorise/mapper/ProfileMapper.java
  src/main/java/com/uplus/ojorise/mapper/UserMapper.java
  src/main/java/com/uplus/ojorise/service/DipPlanService.java
  src/main/java/com/uplus/ojorise/service/ProfileService.java
  src/main/java/com/uplus/ojorise/service/UserService.java
  src/main/resources/mapper/ProfileMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: enhancement

#44 OJORISE-85-add-list-page-API
  src/main/java/com/uplus/ojorise/controller/BrowsePlanController.java
  src/main/java/com/uplus/ojorise/controller/UserController.java
  src/main/java/com/uplus/ojorise/domain/BrowsePlan.java
  src/main/java/com/uplus/ojorise/mapper/BrowsePlanMapper.java
  src/main/java/com/uplus/ojorise/service/BrowsePlanService.java
  src/main/resources/mapper/BrowsePlanMapper.xml
Labels: enhancement

#43 Ojorise 73 add tong bti api
  src/main/java/com/uplus/ojorise/config/JwtAuthenticationFilter.java
  src/main/java/com/uplus/ojorise/config/SecurityConfig.java
  src/main/java/com/uplus/ojorise/controller/QuestionController.java
  src/main/java/com/uplus/ojorise/controller/TongBTIController.java
  src/main/java/com/uplus/ojorise/domain/Question.java
  src/main/java/com/uplus/ojorise/domain/TongBTI.java
  src/main/java/com/uplus/ojorise/dto/TongBTIPlanResponse.java
  src/main/java/com/uplus/ojorise/dto/TongBTIRequest.java
  src/main/java/com/uplus/ojorise/mapper/QuestionMapper.java
  src/main/java/com/uplus/ojorise/mapper/TongBTIMapper.java
  src/main/java/com/uplus/ojorise/service/QuestionService.java
  src/main/java/com/uplus/ojorise/service/TongBTIService.java
  src/main/resources/application.properties
  src/main/resources/mapper/TongBTIMapper.xml
Labels: enhancement

#46 OJORISE-87-add-chart
  src/main/java/com/uplus/ojorise/config/JwtAuthenticationFilter.java
  src/main/java/com/uplus/ojorise/config/SecurityConfig.java
  src/main/java/com/uplus/ojorise/controller/MyPlanController.java
  src/main/java/com/uplus/ojorise/controller/SurveyController.java
  src/main/java/com/uplus/ojorise/domain/MyPlan.java
  src/main/java/com/uplus/ojorise/domain/Plan.java
  src/main/java/com/uplus/ojorise/mapper/MyPlanMapper.java
  src/main/java/com/uplus/ojorise/service/MyPlanService.java
  src/main/resources/application.properties
  src/main/resources/mapper/MyPlanMapper.xml
  src/main/resources/mapper/PlanMapper.xml
Labels: enhancement

#47 OJORISE-89-fix-profile-api
  src/main/java/com/uplus/ojorise/config/JwtAuthenticationFilter.java
  src/main/java/com/uplus/ojorise/config/SecurityConfig.java
  src/main/java/com/uplus/ojorise/domain/Profile.java
  src/main/java/com/uplus/ojorise/domain/Question.java
  src/main/resources/mapper/ProfileMapper.xml
Labels: enhancement

#48 OJORISE-90-fix-browse-api
  src/main/java/com/uplus/ojorise/controller/BrowsePlanController.java
  src/main/java/com/uplus/ojorise/service/BrowsePlanService.java
  src/main/resources/mapper/BrowsePlanMapper.xml
Labels: bug, enhancement

#49 OJORISE-92-fix-dipplan-api
  src/main/java/com/uplus/ojorise/controller/DipPlanController.java
  src/main/java/com/uplus/ojorise/mapper/DipPlanMapper.java
  src/main/java/com/uplus/ojorise/service/DipPlanService.java
Labels: enhancement

#52 OJORISE-99-add-OCR-file-deploy
  src/main/java/com/uplus/ojorise/config/GoogleCredentialInitializer.java
Labels: release

#71 Ojorise 140 fix tongbti mapper
  src/main/java/com/uplus/ojorise/mapper/QuestionMapper.java
  src/main/resources/mapper/QuestionMapper.xml
  src/main/resources/mapper/TongBTIMapper.xml
Labels: bug
